apiVersion: v1
kind: Service
metadata:
  name: main-servlet-service
spec:
  selector:
    app: main-servlet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000 # Or any port your application listens on
  type: NodePort
